name: guardian_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Networking
  retrofit: ^4.0.1
  dio: 5.3.3
  url_launcher: ^6.1.14
  http: ^1.1.0

  # Storage 
  drift: ^2.12.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  

  # State Management
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.20.1

  # UI
  cached_network_image: ^3.2.0

  # Other
  freezed_annotation: ^2.4.1
  auto_route: ^7.8.3
  json_annotation: ^4.8.1
  path : ^1.8.3

  # DI 
  get_it: ^7.6.0
  injectable: 2.3.2
  auto_mappr_annotation: ^2.1.0
  equatable: ^2.0.5
  url_launcher: ^6.1.14
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  injectable_generator: ^2.4.1
  retrofit_generator: ^7.0.8
  drift_dev: ^2.12.1
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  auto_mappr: ^2.1.1
  bloc_test: ^9.1.4
  test: ^1.24.3
  mockito: ^5.4.2


flutter:

  uses-material-design: true

  assets:
      - assets/json/